database:
  type: mysql
  sqlite:
    file: "factions.sqlite"
  mysql:
    host: localhost
    username: root
    password: ""
    schema: "piggyfactions"
  worker-limit: 1
economy:
  provider: economyapi
factions:
  blacklisted-names:
    - staff
    - owner
    - admin
    - mojang
  power:
    default: 0
    min: 0
    max: 10
    per:
      death: -2
      hour: 2
  claims:
    blacklisted-worlds: []
    cost: 1
tags:
  rank-map:
    leader: "^"
    officer: "*"
    member: "+"
    recruit: "-"
  no-faction: ""
  no-power: 0
  no-rank: ""
