database:
  type: mysql
  sqlite:
    file: "factions.sqlite"
  mysql:
    host: localhost
    username: root
    password:
    schema: "dapigguy"
  worker-limit: 1
#economy:
  #provider: economyapi
factions:
  power:
    default: 0
    max: 10
    per:
      death: -2
      hour: 2
  claims:
    cost: 1